#! /bin/sh
### BEGIN INIT INFO
# Provides:          vision
# Required-Start:    $network
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:	     0 1 6
# Short-Description: provide the FRC Vision Server 
### END INIT INFO

PATH=/sbin:/bin

. /lib/lsb/init-functions

do_start () {
	echo "tried to start" >>/media/test
	exec /home/pi/Vision/VisionServer 2>&1 >>/media/VisionLog &
}

case "$1" in
  start)
	do_start
	;;
  restart|reload|force-reload)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
  stop)
	# No-op
	/usr/bin/killall VisionServer
	;;
  *)
	echo "Usage: $0 start|stop" >&2
	exit 3
	;;
esac
